# Generated by Django 5.1.4 on 2025-06-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cimage',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
