# Generated by Django 5.1.4 on 2025-06-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
