# Generated by Django 5.1.4 on 2025-06-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
